CREATE OR REPLACE 
PACKAGE BODY GESTION
IS 

PROCEDURE CREAR_DEP
IS 
BEGIN 
	CREATE TABLE DEPT(
		NOMBRE VARCHAR2(30),
		PRESUPUESTO NUMBER(10),
		NUMERO_DEP NUMBER(10),
		CONSTRAINT FK_DEPT FOREIGN KEY(NOMBRE)
	);
END CREAR_DEP;

FUNCTION NUM_DEP (NOMBRE_DEPT VARCHAR2) RETURN NUMBER IS
BEGIN
	SELECT NUMERO_DEP
	FROM DEPT D
	WHERE D.NOMBRE = NOMBRE_DEPT;
END NUM_DEP;

PROCEDURE MOSTRAR_DEP (NUM_DEP NUMBER)
IS
BEGIN
	SELECT D.NOMBRE
	FROM DEPT D
	WHERE D.NUMERO_DEP = NUM_DEP;
END MOSTRAR_DEP;

PROCEDURE BORRAR_DEP (NUM_DEP NUMBER)
IS
BEGIN
	DELETE FROM DEPT D WHERE NUM_DEP = D.NUMERO_DEP;
END BORRAR_DEP;

PROCEDURE MODIFICAR_DEP(NUM_DEP NUMBER, PRESUPUESTO1 NUMBER)
IS
BEGIN
	UPDATE DEPT D SET D.NUMERO_DEP = NUM_DEP, D.PRESUPUESTO = PRESUPUESTO1;
END MODIFICAR_DEP;

----------------------------------
BEGIN
	CREAR_DEP;
END;

SELECT NUM_DEP(1, 100) FROM DUAL;
SELECT MOSTRAR_DEP('CURRITO') FROM DUAL;
SELECT BORRAR_DEP(1) FROM DUAL;
SELECT MODIFICAR_DEP(1, 200) FROM DUAL;
