--1
SELECT *
FROM (SELECT A.NOMBRE, A.APELLIDOS
		FROM AFICIONADOS a, EJEMPLARESMARIPOSAS e
		WHERE A.DNI=E.DNI_CAPTURA
		GROUP BY A.NOMBRE,A.APELLIDOS
		ORDER BY COUNT(E.NOMBRE_ESPECIE) DESC)
WHERE ROWNUM=1;

--PARA COMPROBAR QUIEN ES EL QUE MÁS HA CAPTURADO
/*SELECT A.NOMBRE ,COUNT(E.TIPO_EJEMPLAR) 
FROM EJEMPLARESMARIPOSAS e, COLECCIONES c , AFICIONADOS a 
WHERE E.DNI_COLECCION = C.DNI AND C.DNI = A.DNI 
GROUP BY A.NOMBRE  ;*/

--2
SELECT E2.NOMBRE_ESPECIE 
FROM EJEMPLARESMARIPOSAS e2 
WHERE E2.TIPO_EJEMPLAR NOT IN (SELECT E.TIPO_EJEMPLAR  
							FROM EJEMPLARESMARIPOSAS e
							WHERE E.TIPO_EJEMPLAR LIKE '%L%');
						
--3
SELECT *
FROM (SELECT A.*
		FROM AFICIONADOS a , COLECCIONES c 
		WHERE A.DNI = C.DNI
		ORDER BY C.PRECIO_ESTIMADO DESC)
WHERE ROWNUM=1;
						
--4
SELECT A.DNI 
FROM AFICIONADOS a
WHERE A.DNI IN (SELECT e.DNI_COLECCION 
				FROM EJEMPLARESMARIPOSAS e 
				WHERE E.NOMBRE_ESPECIE LIKE 'Saturnia Pavonia');

--5
SELECT G.NOMBRE_FAMILIA , G.NOMBRE_GENERO , E2.NOMBRE_ESPECIE 
FROM ESPECIES e2 , GENEROS g 
WHERE E2.NOMBRE_GENERO = G.NOMBRE_GENERO 
AND E2.NOMBRE_ESPECIE NOT IN(SELECT E.NOMBRE_ESPECIE 
							FROM EJEMPLARESMARIPOSAS e);
			
--6
SELECT A.*
FROM AFICIONADOS a 
WHERE A.DNI IN (SELECT E.DNI_CAPTURA 
			FROM EJEMPLARESMARIPOSAS e)
			AND A.DNI NOT IN (SELECT C.DNI 
			FROM COLECCIONES c );
					
--7
				
SELECT  F.NOMBRE_FAMILIA 
FROM FAMILIAS f , GENEROS g , ESPECIES e 
WHERE F.NOMBRE_FAMILIA = G.NOMBRE_FAMILIA 
AND G.NOMBRE_GENERO = E.NOMBRE_GENERO 
AND (E.NOMBRE_ESPECIE LIKE 'A%' OR E.NOMBRE_ESPECIE LIKE 'a')
GROUP BY F.NOMBRE_FAMILIA 
HAVING COUNT(E.NOMBRE_ESPECIE)>5
ORDER BY F.NOMBRE_FAMILIA DESC;
					
					
--8
SELECT *
FROM (SELECT E.NOMBRE_ESPECIE, A.NOMBRE , C.DNI 
	FROM EJEMPLARESMARIPOSAS e ,COLECCIONES c , AFICIONADOS a 
	WHERE E.DNI_CAPTURA = A.DNI 
	AND A.DNI = C.DNI 
	ORDER BY E.TAMANO DESC)
WHERE ROWNUM=1;
			
--9
SELECT DISTINCT E2.NOMBRE_CIENTIFICO 
FROM ESPECIES e2 , EJEMPLARESMARIPOSAS e3 
WHERE E2.NOMBRE_ESPECIE = E3.NOMBRE_ESPECIE 
AND E3.TAMANO >(SELECT AVG(NVL(E.TAMANO,0))
FROM EJEMPLARESMARIPOSAS e); 
			
--10
SELECT Z.PROVINCIA 
FROM ZONLOCPRO z 
WHERE Z.NOMBRE_ZONA NOT IN (SELECT E.NOMBRE_ZONA 
						FROM EJEMPLARESMARIPOSAS e); 
						
--11
SELECT *
FROM (SELECT E.SEXO
		FROM EJEMPLARESMARIPOSAS e 
		GROUP BY E.SEXO
		ORDER BY COUNT(SEXO) ASC)
WHERE ROWNUM=1;

/*SELECT COUNT(E.SEXO) 
FROM EJEMPLARESMARIPOSAS e
WHERE E.SEXO LIKE '%M%'; 
						--PARA COMPROBAR CUANTOS HAY DE CADA SEXO
SELECT COUNT(E.SEXO) 
FROM EJEMPLARESMARIPOSAS e
WHERE E.SEXO LIKE '%I%'; 
					
SELECT COUNT(E.SEXO) 
FROM EJEMPLARESMARIPOSAS e
WHERE E.SEXO LIKE '%H%'; */
					
--12
CREATE VIEW NOMBRESC
(NOMBRES_COMUNES,NOMBRES_CIENTIFICOS,NOMBRE_ZONA)
AS
SELECT DISTINCT E.NOMBRE_ESPECIE , E2.NOMBRE_CIENTIFICO ,E.NOMBRE_ZONA 
FROM EJEMPLARESMARIPOSAS e , ESPECIES e2 
WHERE E.NOMBRE_ESPECIE = E2.NOMBRE_ESPECIE 
AND EXTRACT(YEAR FROM E.FECHA_CAPTURA) BETWEEN 1996 AND 1997
ORDER BY E.NOMBRE_ZONA;  
		
--AQUI LO COMPROBAMOS
SELECT NOMBRES_COMUNES,NOMBRES_CIENTIFICOS,NOMBRE_ZONA
FROM NOMBRESC;


--13
SELECT Z.LOCALIDAD , Z.PROVINCIA 
FROM EJEMPLARESMARIPOSAS e JOIN ZONLOCPRO z 
ON E.NOMBRE_ZONA = Z.NOMBRE_ZONA
GROUP BY Z.LOCALIDAD , Z.PROVINCIA 
HAVING COUNT(E.NOMBRE_ESPECIE)>6
ORDER BY COUNT(E.NOMBRE_ESPECIE);





						